### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by victorDigital** [dnorhoj/LectioCal#3]
Hi there, Thank you for creating this wonderful little script. When setting up, I ran into this small roadblock. I hope you can help.

```sh
C:\Users\Victor\Desktop\LectioCal-1.1.0\src>python main.py
Starting Lectio.py ft. CalDAV
Traceback (most recent call last):
  File "C:\Users\Victor\Desktop\LectioCal-1.1.0\src\main.py", line 287, in <module>
    sync.sync()
  File "C:\Users\Victor\Desktop\LectioCal-1.1.0\src\main.py", line 220, in sync
    sched_lookup = [self._get_module_id(module) for module in sched]
  File "C:\Users\Victor\Desktop\LectioCal-1.1.0\src\main.py", line 220, in <listcomp>
    sched_lookup = [self._get_module_id(module) for module in sched]
  File "C:\Users\Victor\Desktop\LectioCal-1.1.0\src\main.py", line 92, in _get_module_id
    return "lecmod"+re.search(r"absid=(.*?)&", module.url)[1]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by dnorhoj** [comment]
Hmm I'll look into that soon

**Comment by dnorhoj** [comment]
Have looked into it and it seems that it is a problem with [Lectio.py](https://github.com/dnorhoj/Lectio.py). So it will probably take a bit of time to fix...

**Comment by dnorhoj** [comment]
Looks like the problem is that a module can have no URL, I have patched this bug in Lectio.py but will have to make some modifications here...

[Lectio.py update](https://github.com/dnorhoj/lectio.py/releases/tag/0.1.1)

**Comment by dnorhoj** [comment]
Fixed!
